[package]
name = "ckb-script"
version = "0.26.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"

[features]
default = ["logging", "asm"]

asm = ["ckb-vm/asm"]
logging = ["ckb-logger"]

[dependencies]
ckb-script-data-loader = { path = "data-loader" }
byteorder = "1.3.1"
ckb-types = {path = "../util/types"}
ckb-hash = {path = "../util/hash"}
ckb-vm = { version = "0.18.0", default-features = false }
faster-hex = "0.4"
ckb-logger = { path = "../util/logger", optional = true }
serde = "1.0"
serde_derive = "1.0"
ckb-error = { path = "../error" }
failure = "0.1.5"
ckb-chain-spec = { path = "../spec" }

[dev-dependencies]
proptest = "0.9"
ckb-db = { path = "../db" }
ckb-store = { path = "../store" }
ckb-test-chain-utils = { path = "../util/test-chain-utils" }
tiny-keccak = "1.4"
ckb-crypto = { path = "../util/crypto"}
